[package]
name = "jugalbandi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp1-core = { git = "https://github.com/succinctlabs/sp1.git" }
actix-web = "4"
serde = "1.0.197"
serde_json = "1.0"
lc3-zk-vm = { git = "https://github.com/manojkgorle/lc3.git" }